# Generated by Django 4.1.2 on 2022-12-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('selling_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('aroma', models.CharField(max_length=150)),
                ('appearance', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Product Image')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='product.category')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
